#!/usr/bin/php
<?php
require_once 'simple_table_generator.class.php';

define( 'MIN_RANK', 1 );
define( 'MAX_RANK', 3 );

// require an input rank, begin date, end date, site
$rank=3;
$begin_date='2019-01-16';
$end_date='2019-02-15';

$stage_list=array(
  'inhome_1'=>array(
    'data'=>null),
  'inhome_2'=>array(
    'data'=>null),
  'inhome_3'=>array(
    'data'=>null),
  'inhome_4'=>array(
    'data'=>null)
);

$common_header_str = array();
$common_header_str[] = sprintf('"DATES","%s - %s"',$begin_date, $end_date);
$str = array();

// get all available sites that have the data for all four inhome interview stages
$site_keys = array();
$site_key_counts = array();
$all_site_total = array();
$total_key_list = array('total_skip','total_unexplained_missing');
$total_key_count = count($total_key_list);
foreach($stage_list as $key=>$value)
{
  $$key = new simple_table_generator($key, $rank, $begin_date, $end_date);
  $$key->build_table_data();
  $data = $$key->get_site_data_list();
  unset($data['ALL']);
  $stage_list[$key]['data'] = $data;
  $keys = array_keys($data);
  $site_keys[] = $keys;
  $site_key_counts[] = count($keys);
  $all_site_total[$key] = array_combine($total_key_list,array_fill(0,$total_key_count,0));
}

$idx = array_search(min($site_key_counts),$site_key_counts);
$site_keys = $site_keys[$idx];

$stage_key_list = array_keys($stage_list);
$all_site_total['total_interview'] = 0;

$file_str_sites = array();

$compound_site_data_list = array();

foreach($site_keys as $site)
{
  $tech_data = array();
  $site_data = array();
  $site_data['total_interview'] = 0;
  foreach($stage_list as $stage_key=>$value)
  {
    // for the current stage, get the number of skips, missing for each tech
    $data = $value['data'][$site]['technicians'];
    $site_stage_total = array_combine($total_key_list,array_fill(0,$total_key_count,0));
    foreach($data as $tech_key=>$tech_totals)
    {
      //if('NA' == $tech_key) continue;
      if(!array_key_exists($tech_key,$tech_data))
      {
        $tech_data[$tech_key] = array();
        $tech_data[$tech_key]['total_interview'] = $tech_totals['total_tech'];
        $site_data['total_interview'] += $tech_totals['total_tech'];
      }
      $total_list = array();
      foreach($total_key_list as $total_key)
      {
        $total_val = intval($tech_totals[$total_key]);
        $all_site_total[$stage_key][$total_key] += $total_val;
        $site_stage_total[$total_key] += $total_val;
        $total_list[] = $total_val;
      }
      $tech_data[$tech_key][$stage_key]['total_list'] = $total_list;
    }

    // current site level stage totals
    $site_data[$stage_key]['total_list'] = array_values($site_stage_total);
  }

  $total_site_interview = $site_data['total_interview'];
  $all_site_total['total_interview'] += $total_site_interview;

  $compound_site_data_list[$site]['site_data'] = $site_data;
  $compound_site_data_list[$site]['tech_data'] = $tech_data;
}

foreach($compound_site_data_list as $site => $data)
{
  $tech_data = $data['tech_data'];
  $site_data = $data['site_data'];
  $file_str = array();
  $file_str[] = sprintf('"SITE","%s"',$site);
  $file_str = array_merge($file_str,$common_header_str);
  $header_str = array();

  $file_str[] = '""'; // row separator
  $file_str[]='"NUMBER OF SKIPS, MISSING"';

  // headings of stage names with separators for total columns below
  $stage_heading_list = array();
  foreach($stage_key_list as $stage)
  {
    $stage_heading_list[] = $stage;
    $stage_heading_list[] = '';
  }
  $file_str[] =
    str_replace('_', ' ',strtoupper(
    '"","' .
    implode('","',$stage_heading_list) .
    '"'));

  // sub-headings
  $file_str[] =
    '"Tech",'.
    implode(',',array_fill(0,count($stage_key_list),'"Total Skips","Total Missing"')) .
    ',"Total Interviews (%)"';

  $total_site_interview = $site_data['total_interview'];
  foreach($tech_data as $tech=>$values)
  {
    $str = array();
    $str[] = $tech;
    // append the stage category totals and percentage of interviews
    foreach($stage_key_list as $stage)
    {
      if(!array_key_exists($stage,$values) || !array_key_exists('total_list',$values[$stage]))
      {
        util::out(sprintf('WARNING: site %s tech %s has no data on %s',$site,$tech,$stage));
        $str = array_merge($str,array_fill(0,$total_key_count,0));
      }
      else
        $str = array_merge($str,$values[$stage]['total_list']);
    }
    $str[] = sprintf('%s (%s)',
      $values['total_interview'],
      (0 == $total_site_interview ? 0 : round(100.0*$values['total_interview']/$total_site_interview)));
    $file_str[] = '"'.implode('","',$str).'"';
  }

  $str = array('TOTAL');
  foreach($stage_key_list as $stage)
  {
    $str = array_merge($str,$site_data[$stage]['total_list']);
  }

  $str[] = sprintf('%s (%s)', $total_site_interview,
      (0 == $all_site_total['total_interview'] ? 0 : round(100.0*$total_site_interview/$all_site_total['total_interview'])));
  $file_str[] = '"'.implode('","', $str).'"';

  //var_dump($site_data);dd
  $file_str_sites[$site] = $file_str;
  util::out($site);
}

$overall_str = array('OVERALL');
$summary_str = array('OVERALL BY STAGE');
$summary_str[] =  '"'. implode('","',array('Stage','Total Skips','Total Missing')) . '"';
foreach($stage_key_list as $stage)
{
  $summary_str[] = '"' . implode('","',array_merge(array(
    str_replace('_', ' ',strtoupper($stage))),$all_site_total[$stage])) . '"';

  //$total_stage = array_sum(array_values($all_site_total[$stage]));
  foreach($all_site_total[$stage] as $key=>$value)
  {
    $overall_str[] = $value;
    //$str[] = sprintf('%s (%s)',$value,
    //(0 == $total_stage ? 0 : round(100.0*$value/$total_stage)));
  }
}

$overall_str[] = $all_site_total['total_interview'];
$overall_str = '"'.implode('","', $overall_str).'"';

$filename = sprintf('/home/dean/files/webapps/qac/aux/inhome_skip_report_wave_%d_%s_%s.csv',
 $rank,
 str_replace('-','',$begin_date),
 str_replace('-','',$end_date));

$file = fopen($filename,'w');
foreach($file_str_sites as $site=>$file_str)
{
  foreach($file_str as $item_str)
    fwrite($file, $item_str . PHP_EOL );
  fwrite($file, $overall_str . PHP_EOL );
  fwrite($file, '""' . PHP_EOL );
}

fwrite($file, '""' . PHP_EOL );
foreach($summary_str as $str)
{
  fwrite($file, $str . PHP_EOL );
}

fclose($file);
