#!/usr/bin/php
<?php
require_once '../settings.ini.php';
require_once $SETTINGS['path']['PHP_UTIL'].'/database.class.php';
require_once $SETTINGS['path']['PHP_UTIL'].'/util.class.php';
require_once $SETTINGS['path']['PHP_UTIL'].'/phplot-6.2.0/phplot.php';

define( 'MIN_RANK', 1 );
define( 'MAX_RANK', 3 );

$ttf_path = $SETTINGS['path']['PHP_UTIL'].'/fonts/msttcorefonts';

function fmt_label($value,$arg,$row)
{
  return sprintf('%s (%s)',$arg[$row][0],$arg[$row][1]);
}


function plot_histogram($filename,$title,$xtitle,$plotdata, $plotpoints,$plotareas=null)
{
  global $ttf_path;

  $plot = new PHPlot(800, 600);
  //$plot->SetTTFPath($ttf_path);
  //$plot->SetFontTTF('y_label','Arial_Bold.ttf',10);
  $plot->SetImageBorderType('plain');
  $plot->SetOutputFile($filename);
  $plot->SetPrintImage(0);
  $plot->SetIsInline(true);

  $plot->SetTitle($title);
  $plot->SetYTitle('Frequency');
  $plot->SetXTitle($xtitle);
  $plot->SetDrawXGrid(true);
  $plot->SetDrawYGrid(true);
  $plot->SetPrecisionY(0);
  $plot->SetPrecisionX(0);

  $plot->SetDataColors('navy');
  $plot->SetPlotType('lines');
  $plot->SetDataType('data-data');
  $plot->SetDataValues($plotdata);

  $plot->SetXLabelType('data');
  $plot->SetNumXTicks(10);
  $plot->SetXTickLabelPos('plotdown');
  $plot->SetYLabelType('data');
  $plot->DrawGraph();

  if(null!=$plotareas)
  {
    $plot->SetPlotType('squaredarea');
    $plot->SetDataType('data-data');
    $plot->SetDataValues($plotareas);
    $num_col = count($plotareas);
    $colors=array();
    for($i=0;$i<$num_col;$i++)
    {
      if($i%2==0)$colors[]='yellow';
      else $colors[]='green';
    }

    $plot->SetDataColors(
      $colors );
    $plot->DrawGraph();

    $plot->SetDataColors('navy');
    $plot->SetPlotType('lines');
    $plot->SetDataType('data-data');
    $plot->SetDataValues($plotdata);
    $plot->DrawGraph();
  }

  $plot->SetXTickLabelPos('none');
  $plot->SetXTickPos('none');
  $plot->SetDrawXGrid(false);
  $plot->SetDrawYGrid(false);
  $plot->SetTitle('');
  $plot->SetYTitle('');
  $plot->SetXTitle('');
  $plot->SetPlotType('points');
  $plot->SetDataType('data-data');
  $plot->SetDataValues($plotpoints);
  $plot->SetYDataLabelPos('plotin');
  $plot->SetYDataLabelType('custom','fmt_label',$plotpoints);
  $plot->SetDataColors('red');
  $plot->DrawGraph();

  $plot->PrintImage();
}

function get_stage_from_type( $_file_type )
{
  // short form names to stage table names lookup
  //
  $type_list= array(
    'cine'=>'carotid_intima',
    'still'=>'carotid_intima',
    'sr'=>'carotid_intima',
    'ecg'=>'ecg',
    'retinal'=>'retinal_scan',
    'hip'=>'dual_hip_bone_density',
    'wbody'=>'whole_body_bone_density',
    'arm'=>'forearm_bone_density',
    'lateral'=>'lateral_bone_density',
    'spine'=>'spine_bone_density',
    'cog'=>'cognitive_test',
    'dot'=>'cognition_recording',
    'wor'=>'cognition_recording',
    'col'=>'cognition_recording',
    'fas'=>'cognition_recording',
    'reyi'=>'inhome_cognition_recording',
    'reyii'=>'inhome_cognition_recording',
    'anml'=>'inhome_cognition_recording',
    'coun'=>'inhome_cognition_recording',
    'alph'=>'inhome_cognition_recording',
    'altr'=>'inhome_cognition_recording'
  );
  if(!array_key_exists($_file_type,$type_list))
  {
    util::out('ERROR: failed to find type '. $_file_type);
    die();
  }
  $stage = $type_list[$_file_type];
  return $stage;
}

function get_stage_index_from_type( $_file_type )
{
  $type_list=array(
    'cine'=>array(
        1=>array(3,4,5,8,9,10),2=>array(1,6),3=>array(1,6)),
    'sr'=>array(
        1=>array(2,7),2=>array(2,7),3=>array(2,7)),
    'still'=>array(
        1=>array(1,6),2=>array(3,4,5,8,9,10),3=>array(3,4,5,8,9,10)),
    'lateral'=>array(
        1=>array(1),2=>array(1),3=>array(1)),
    'arm'=>array(
        1=>array(1),2=>array(1),3=>array(1)),
    'hip'=>array(
        1=>array(1,2),2=>array(1,2),3=>array(1,2)),
    'spine'=>array(
        1=>null,2=>array(1),3=>array(1)),
    'wbody'=>array(
        1=>array(1),2=>array(1),3=>array(1)),
    'retinal'=>array(
        1=>array(1,2),2=>array(1),3=>array(1)),
    'ecg'=>array(
        1=>array(1),2=>array(1),3=>array(1)),
    'cog'=>array(
        1=>array(1),2=>array(1),3=>array(1)),
    'dot'=>array(
      1=>array(1),2=>array(1),3=>array(1)),
    'wor'=>array(
      1=>array(2),2=>array(2),3=>array(2)),
    'col'=>array(
      1=>array(3),2=>array(3),3=>array(3)),
    'fas'=>array(
      1=>array(4,5,6),2=>array(4,5,6),3=>array(4,5,6)),
    'reyi'=>array(
      1=>array(1),2=>array(1),3=>array(1)),
    'reyii'=>array(
      1=>array(6),2=>array(6),3=>array(6)),
    'anml'=>array(
      1=>array(2),2=>array(2),3=>array(2)),
    'coun'=>array(
      1=>array(3),2=>array(3),3=>array(3)),
    'alph'=>array(
      1=>array(4),2=>array(4),3=>array(4)),
    'altr'=>array(
      1=>array(5),2=>array(5),3=>array(5)),
  );
  if(!array_key_exists($_file_type,$type_list))
  {
    util::out('ERROR: failed to find type '. $_file_type);
    die();
  }
  $index = $type_list[$_file_type];
  return $index;
}

function get_bin_size_from_type( $_file_type )
{
  $bin=1000;
  $type_list=array(
    'cine'=>50000,
    'sr'=>10,
    'still'=>100,
    'ecg'=>100,
    'arm'=>100,
  );
  if(array_key_exists($_file_type,$type_list))
  {
    $bin=$type_list[$_file_type];
  }
  return $bin;
}

function get_scale_factor( $_min )
{
  $fac = array(1.0,1024.0,1048576.0,1073741824.0);
  // get min len where val > 0
  $minlen=10000000000;
  $minscale=1.0;
  foreach($fac as $scale)
  {
     $val = floor($_min / $scale);
     $len = strlen( (string)$val );
     $x = ceil(log10($_min/$scale));

     util::out(sprintf('%s %s %s %s %s',$_min, $scale, $val, $len, $x));
     //if($len<$minlen && 0<$val)
     if($val>0 && $x>1)
     {
       //$minlen=$len;
       $minlen=$x;
       $minscale=$scale;
     }
  }
  return $minscale;
}

$rank = 1; // set default
$type = 'still';
$user_bin = null;
$user_perc_bin = null;
if( 3 == $argc )
{
  $rank = $argv[1];
  $type = $argv[2];
}
else if( 4 == $argc )
{
  $rank = $argv[1];
  $type = $argv[2];
  $user_bin = $argv[3];
}
else if( 5 == $argc )
{
  $rank = $argv[1];
  $type = $argv[2];
  $user_bin = $argv[3];
  $user_perc_bin = $argv[4];
}
else
{
  util::out(
    'usage: distribution_plot rank [1,2,3,0]\n'.
    'type [cine,still,sr,ecg,retinal,hip,wbody,arm,lateral,spine,cog,dot,wor,col,fas,reyi,reyii,anml,coun,alph,altr] <bin_size> <percentile>' );
  die();
}

$no_rank = false;
if($rank < MIN_RANK || $rank > MAX_RANK )
{
  util::out('ignoring rank: all ranks will be used');
  $no_rank = true;
}

$db = new database(
  $SETTINGS['db']['DB_SERV'],
  $SETTINGS['db']['DB_USER'],
  $SETTINGS['db']['DB_PASS'],
  $SETTINGS['db']['DB_NAME'] );

$stage = get_stage_from_type($type);
$index_list = get_stage_index_from_type($type);
if(false == $no_rank && null==$index_list[$rank])
{
  util::out(sprintf('data does not exist for type %s for rank %d',$type,$rank));
  die();
}

$union_sql=array();
$rank_list=null;
if($no_rank)
{
  $rank_list=range(MIN_RANK,MAX_RANK);
}
else
{
  $rank_list=array($rank);
}

foreach($rank_list as $rank_item)
{
  foreach($index_list[$rank_item] as $item)
  {
    $union_sql[]=sprintf(
      ' ( '.
      '  select cast(trim("}" from substring_index(substring_index(qcdata,",",%d),":",-1)) as unsigned) as filesize, '.
      '  start_date, '.
      '  concat(ifnull(t.name,"NA"),"(",site.name,")") as tech, '.
      '  site.name as site, '.
      '  s.id as stage_id '.
      '  from interview i'.
      '  join stage s on i.id=s.interview_id'.
      '  join site on site.id=i.site_id '.
      '  left join technician t on t.id=s.technician_id and t.site_id=site.id '.
      '  where rank=%d '.
      '  and qcdata is not null '.
      '  and s.name like "%s%%" '.
      ' ) ', $item, $rank_item, $stage );
  }
}

$sql = 'create temporary table tmp as select ';
if(1<count($union_sql))
{
  $sql = $sql .
    ' filesize, start_date, tech, site, stage_id from ( '.
    implode(' union all ', $union_sql ) .
    ') as t where filesize > 0 order by start_date, stage_id';
}
else
{
  $sql = $sql .
    ' filesize, start_date, tech, site, stage_id from ( '.
    $union_sql[0] .
    ') as t where filesize > 0 order by start_date, stage_id';
}

$db->execute($sql);

util::out($sql);

$sql =
  'select min(filesize) as fmin, max(filesize) as fmax, '.
  'stddev(filesize) as fstd, avg(filesize) as fave '.
  'from tmp';

$res = $db->get_row($sql);

$fmin = $res['fmin'];
$fmax = $res['fmax'];
$fave = $res['fave'];
$fstd = $res['fstd'];

$sql =
  'select filesize, count(filesize) as freq '.
  'from tmp '.
  'group by filesize '.
  'order by freq desc '.
  'limit 1';

$res = $db->get_row($sql);
$mode = $res['filesize'];

$scale = get_scale_factor( $fmin );
$mscale = get_scale_factor( $fmax );
if( 1.0 == $scale && $mscale>$scale )
{
  $scale = $mscale;
}
$fsmin = floor($fmin/$scale);
$fsmax = ceil($fmax/$scale);

$bin = 1;
if(null == $user_bin)
{
  $bin = ceil(log10($fsmax-$fsmin));
}
else
{
  $bin = $user_bin;
}

$bmin = max(0,$bin*floor($fsmin/$bin)-$bin);
$bmax = $bin*(floor($fsmax/$bin)+1);
$bin_range = range($bmin,$bmax,$bin);
$bin_count = count($bin_range);

util::out(sprintf('filesize ave std: %s %s',$fave, $fstd));
util::out(sprintf('filesize [min max range]: [%d %d %d]',$fmin,$fmax, $fmax-$fmin));
util::out(sprintf('scaled   [min max range]: [%d %d %d]',$fsmin,$fsmax, $fsmax-$fsmin));
util::out(sprintf('bin size [range]: %d [%d %d]',$bin,$bmin,$bmax));
util::out('number of bins: ' . $bin_count);

$set = range(-3,3);
$std = array();
foreach($set as $num)
{
  $std[] = $bin*floor((($fave+$num*$fstd)/$scale)/$bin);
}

util::out('std deviations: '. implode(',',$std));

$histo = array_combine($bin_range,array_fill(0,$bin_count,0));

$data = $db->get_all('select * from tmp order by start_date');

$db->execute('drop table tmp');

foreach($data as $items)
{
  $fsz = $items['filesize'];
  $curr = $bin*floor($fsz/$scale/$bin);
  if(in_array($curr,$bin_range))
    $histo[$curr]++;
}

$freqmax = max(array_values($histo));
$mode_bin = array_search($freqmax,$histo);

util::out(sprintf('mode: %s, scaled mode: %s, freq: %s, bin: %s', $mode, intval(round($mode/$scale)), $freqmax, $mode_bin));

$mode=intval(round($mode/$scale));

$plotdata = array();
$plotpoints = array();
$label_list = array();
$area = array_sum(array_values($histo));
$cum_sum = 0;
$last_bin = 0;
$percentile_bin = 10;
if(null != $user_perc_bin && $user_perc_bin>0 && $user_perc_bin<100)
{
  $percentile_bin = $user_perc_bin;
}
$last_percentile = $percentile_bin;
$current_percentile_bin = $percentile_bin;
$percentile_list[$current_percentile_bin] = array(
  'freq'=>array(),
  'ord'=>0,
  'endord'=>null,
  'endpercentile'=>null,
  'perc'=>array());

foreach($histo as $filesize_bin=>$frequency)
{
  // compute the percentile for the current bin
  $cum_sum += $frequency;
  $percent = 100.0*$cum_sum/$area;
  $percentile = intval(round($percent));

  // scale the percentile for line plotting
  $plotdata[] = array('',$filesize_bin,$frequency, $percentile*$freqmax/100.0);

  if($percentile > $current_percentile_bin)
  {
    $percentile_list[$current_percentile_bin]['endord']=$filesize_bin;
    $percentile_list[$current_percentile_bin]['endpercentile']=$percentile;
    $next_percentile_bin = min($current_percentile_bin+$percentile_bin,100-$percentile_bin);
    if($next_percentile_bin != $current_percentile_bin)
    {
      $current_percentile_bin = $next_percentile_bin;
      $percentile_list[$current_percentile_bin] = array(
        'freq'=>array(),
        'ord'=>$filesize_bin,
        'endord'=>null,
        'endpercentile'=>null,
        'perc'=>array());
    }
  }
  $percentile_list[$current_percentile_bin]['freq'][] = $frequency;
  $percentile_list[$current_percentile_bin]['perc'][] = $percent;

  if(in_array($filesize_bin,$std))
  {
    $index = array_search($filesize_bin,$std);
    $height = $index%2 == 0 ? $freqmax : 0.975*$freqmax;
    $label = ($index<3?((-3+$index).'SD'):($index>3?('+'.(-3+$index).'SD'):'AVG'));
    if(!in_array($label,$label_list))
    {
      $plotpoints[] = array($label,$filesize_bin,$height);
      $label_list[] = $label;
    }
  }
  else if($filesize_bin==$mode_bin)
  {
    $label = 'MOD';
    if(!in_array($label,$label_list))
    {
      $plotpoints[] = array($label,$mode,1.025*$freqmax);
      $label_list[] = $label;
    }
  }
  $last_bin = $filesize_bin;
  $last_percentile = $percentile;
}
$percentile_list[$current_percentile_bin]['endord'] = $last_bin;
$percentile_list[$current_percentile_bin]['endpercentile'] = $last_percentile;

util::out('cumulative freq: ' . $cum_sum);
$cum_sum = 0;
$plotareas=array();
$percentile_values = array_keys($percentile_list);
$default_row = array_fill(0,count($percentile_values),0);
$last_row;
foreach($percentile_list as $percentile=>$data)
{
  util::out(sprintf('percentile: %s -> %s [%s -> %s] n: %d  perc range: [%7.3lf => %7.3lf]',
    $percentile,
    $data['endpercentile'],
    $data['ord'],
    $data['endord'],
    //util::time_to_label($data['ord']/60.0),
    //util::time_to_label($data['endord']/60.0),
    count($data['freq']),
    min($data['perc']),
    max($data['perc'])));
  $cum_sum+=array_sum($data['freq']);

  $row = $default_row;
  $id = array_search($percentile,$percentile_values);
  $row[$id] = $percentile * $freqmax/100.0;
  $plotareas[] = array_merge(array('',$data['ord']),$row);
  $last_row = array_merge(array('',$data['endord']),$row);
  $label_x = '';
  $label_y = $row[$id];
  /*
  if($id == 0)
    $label_x = $data['endord'];
  else
    $label_x = $data['ord'];
  */
  if($id != 0)
  {
    $label_x = $data['ord'];
    $label = $label_x;//util::time_to_label($label_x/60.0);
    $plotpoints[] = array($label,$label_x,$label_y);
  }
}
$plotareas[] = $last_row;
util::out('CHECK cumulative freq: ' . $cum_sum);


$filename = sprintf('histogram_%s_%s_%s_%s.csv', ($no_rank ? 'ALL' : $rank), $bin, $percentile_bin, $type);
util::out('writing to ' . $filename);
$file = fopen($filename,'w');

$header = sprintf('"filesize","frequency"') . PHP_EOL;
fwrite($file,$header);
foreach($histo as $bin=>$value)
{
  fwrite($file, sprintf('"%d","%d"',$bin,$value) . PHP_EOL);
}
fclose($file);

$filename = str_replace('.csv','.jpg',$filename);
$title = sprintf( '%s %s distribution', $type, $rank);
$xtitle = 'Scale (' . (1.0==$scale?'bytes':(1024.0==$scale?'Kb':'Mb')).')';
plot_histogram($filename,$title,$xtitle,$plotdata, $plotpoints, $plotareas);
