SELECT "Creating new stage table" AS "";

CREATE TABLE IF NOT EXISTS stage_type (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  update_timestamp TIMESTAMP NOT NULL,
  create_timestamp TIMESTAMP NOT NULL,
  category VARCHAR(45) NOT NULL,
  name VARCHAR(45) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX `uq_category_name` (`category` ASC, `name` ASC))
ENGINE = InnoDB;

INSERT IGNORE INTO stage_type( category, name ) VALUES
( "DCS", "blood" ),
( "DCS", "blood_pressure" ),
( "DCS", "carotid_intima" ),
( "DCS", "cdtt" ),
( "DCS", "chair_rise" ),
( "DCS", "cognition_recording" ),
( "DCS", "cognitive_test" ),
( "DCS", "conclusion_qnaire" ),
( "DCS", "contraindication_qnaire" ),
( "DCS", "deviation_aecrf" ),
( "DCS", "dexa" ),
( "DCS", "dexa_forearm" ),
( "DCS", "dexa_hip" ),
( "DCS", "dexa_lateral" ),
( "DCS", "dexa_qnaire" ),
( "DCS", "dexa_spine" ),
( "DCS", "dexa_whole_body" ),
( "DCS", "disease_qnaire" ),
( "DCS", "ecg" ),
( "DCS", "event_pmt" ),
( "DCS", "fas" ),
( "DCS", "frax" ),
( "DCS", "functional_status" ),
( "DCS", "general_health" ),
( "DCS", "grip_strength" ),
( "DCS", "hearing" ),
( "DCS", "height_weight" ),
( "DCS", "hips_waist" ),
( "DCS", "inhome_qa" ),
( "DCS", "neuro_battery" ),
( "DCS", "neuro_scoring" ),
( "DCS", "osea" ),
( "DCS", "osipv" ),
( "DCS", "osonly" ),
( "DCS", "retinal_scan" ),
( "DCS", "retinal_scan_left" ),
( "DCS", "retinal_scan_right" ),
( "DCS", "sitting_height" ),
( "DCS", "social_network" ),
( "DCS", "spirometry" ),
( "DCS", "standing_balance" ),
( "DCS", "standing_height" ),
( "DCS", "stroop" ),
( "DCS", "time_based_pmt" ),
( "DCS", "tonometer" ),
( "DCS", "tug" ),
( "DCS", "urine" ),
( "DCS", "vision_acuity" ),
( "DCS", "walk" ),
( "DCS", "weight" ),
( "DCSatHome", "body_composition" ),
( "DCSatHome", "os" ),
( "InHome", "inhome_1" ),
( "InHome", "inhome_2" ),
( "InHome", "inhome_3" ),
( "InHome", "inhome_4" ),
( "InHome", "inhome_cognition_recording" ),
( "InHome", "inhome_conclusion_qnaire" ),
( "InHome", "inhome_consent" ),
( "InHome", "inhome_id" );
