-- MySQL Script generated by MySQL Workbench
-- Tue 22 Jan 2019 01:53:27 PM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='';

-- -----------------------------------------------------
-- Schema cosmos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cosmos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cosmos` DEFAULT CHARACTER SET utf8 ;
USE `cosmos` ;

-- -----------------------------------------------------
-- Table `cosmos`.`site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosmos`.`site` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `update_timestamp` TIMESTAMP NOT NULL,
  `create_timestamp` TIMESTAMP NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_name` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosmos`.`technician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosmos`.`technician` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `update_timestamp` TIMESTAMP NOT NULL,
  `create_timestamp` TIMESTAMP NOT NULL,
  `site_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_site_id` (`site_id` ASC),
  UNIQUE INDEX `uq_site_id_name` (`site_id` ASC, `name` ASC),
  CONSTRAINT `fk_technician_site_id`
    FOREIGN KEY (`site_id`)
    REFERENCES `cosmos`.`site` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosmos`.`interview`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosmos`.`interview` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `update_timestamp` TIMESTAMP NOT NULL,
  `create_timestamp` TIMESTAMP NOT NULL,
  `site_id` INT UNSIGNED NOT NULL,
  `start_date` DATE NOT NULL,
  `uid` VARCHAR(10) NOT NULL,
  `barcode` VARCHAR(20) NOT NULL,
  `rank` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_site_id` (`site_id` ASC),
  UNIQUE INDEX `uq_site_id_uid_barcode_rank` (`site_id` ASC, `uid` ASC, `barcode` ASC, `rank` ASC),
  CONSTRAINT `fk_interview_site_id`
    FOREIGN KEY (`site_id`)
    REFERENCES `cosmos`.`site` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosmos`.`stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosmos`.`stage` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `update_timestamp` TIMESTAMP NOT NULL,
  `create_timestamp` TIMESTAMP NOT NULL,
  `interview_id` INT UNSIGNED NOT NULL,
  `technician_id` INT UNSIGNED NULL,
  `name` VARCHAR(45) NOT NULL,
  `missing` TINYINT(1) NULL,
  `contraindicated` TINYINT(1) NULL,
  `comment` VARCHAR(1028) NULL,
  `skip` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_interview_id` (`interview_id` ASC),
  INDEX `fk_technician_id` (`technician_id` ASC),
  UNIQUE INDEX `uq_interview_id_technician_id_name` (`interview_id` ASC, `technician_id` ASC, `name` ASC),
  CONSTRAINT `fk_stage_interview_id`
    FOREIGN KEY (`interview_id`)
    REFERENCES `cosmos`.`interview` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stage_technician_id`
    FOREIGN KEY (`technician_id`)
    REFERENCES `cosmos`.`technician` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosmos`.`indicator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosmos`.`indicator` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `update_timestamp` TIMESTAMP NOT NULL,
  `create_timestamp` TIMESTAMP NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` ENUM('integer', 'float', 'boolean') NOT NULL,
  `value` FLOAT NULL DEFAULT NULL,
  `side` ENUM('left', 'right', 'none') NULL DEFAULT 'none',
  `par_min` FLOAT NULL DEFAULT NULL,
  `par_max` FLOAT NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosmos`.`stage_has_indicator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosmos`.`stage_has_indicator` (
  `stage_id` INT UNSIGNED NOT NULL,
  `indicator_id` INT UNSIGNED NOT NULL,
  `update_timestamp` TIMESTAMP NOT NULL,
  `create_timestamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`stage_id`, `indicator_id`),
  INDEX `fk_indicator_id` (`indicator_id` ASC),
  INDEX `fk_stage_id` (`stage_id` ASC),
  CONSTRAINT `fk_stage_has_indicator_stage_id`
    FOREIGN KEY (`stage_id`)
    REFERENCES `cosmos`.`stage` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stage_has_indicator_indicator_id`
    FOREIGN KEY (`indicator_id`)
    REFERENCES `cosmos`.`indicator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosmos`.`site_stage_cache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosmos`.`site_stage_cache` (
  `site_id` INT UNSIGNED NOT NULL,
  `update_timestamp` TIMESTAMP NOT NULL,
  `create_timestamp` TIMESTAMP NOT NULL,
  `missing` INT NOT NULL DEFAULT 0,
  `contraindicated` INT NOT NULL DEFAULT 0,
  `skip` INT NOT NULL DEFAULT 0,
  `start_date` DATE NOT NULL,
  `stage_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`site_id`),
  INDEX `fk_site_id` (`site_id` ASC),
  CONSTRAINT `fk_site_stage_cache_site_id`
    FOREIGN KEY (`site_id`)
    REFERENCES `cosmos`.`site` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosmos`.`technician_stage_cache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosmos`.`technician_stage_cache` (
  `technician_id` INT UNSIGNED NOT NULL,
  `update_timestamp` TIMESTAMP NOT NULL,
  `create_timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAP,
  `missing` INT NOT NULL DEFAULT 0,
  `contraindicated` INT NOT NULL DEFAULT 0,
  `skip` INT NOT NULL DEFAULT 0,
  `start_date` DATE NOT NULL,
  `stage_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`technician_id`),
  INDEX `fk_technician_id` (`technician_id` ASC),
  CONSTRAINT `fk_technician_stage_cache_technician_id`
    FOREIGN KEY (`technician_id`)
    REFERENCES `cosmos`.`technician` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosmos`.`technician_indicator_cache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosmos`.`technician_indicator_cache` (
  `technician_id` INT UNSIGNED NOT NULL,
  `update_timestamp` TIMESTAMP NOT NULL,
  `create_timestamp` TIMESTAMP NOT NULL,
  `par_under` INT NOT NULL DEFAULT 0,
  `par_within` INT NOT NULL DEFAULT 0,
  `par_above` INT NOT NULL DEFAULT 0,
  `start_date` DATE NOT NULL,
  `stage_name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `side` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `cumulative_average` FLOAT NOT NULL,
  `running_average` FLOAT NOT NULL,
  `count` FLOAT NOT NULL,
  PRIMARY KEY (`technician_id`),
  INDEX `fk_technician_id` (`technician_id` ASC),
  CONSTRAINT `fk_technician_indicator_cache_technician_id`
    FOREIGN KEY (`technician_id`)
    REFERENCES `cosmos`.`technician` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosmos`.`site_indicator_cache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosmos`.`site_indicator_cache` (
  `site_id` INT UNSIGNED NOT NULL,
  `update_timestamp` TIMESTAMP NOT NULL,
  `create_timestamp` TIMESTAMP NOT NULL,
  `par_under` INT NOT NULL DEFAULT 0,
  `par_within` INT NOT NULL DEFAULT 0,
  `par_above` INT NOT NULL DEFAULT 0,
  `start_date` DATE NOT NULL,
  `stage_name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `side` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `cumulative_average` FLOAT NOT NULL,
  `running_average` FLOAT NOT NULL,
  `count` FLOAT NOT NULL,
  PRIMARY KEY (`site_id`),
  INDEX `fk_site_id` (`site_id` ASC),
  CONSTRAINT `fk_site_indicator_cache_site_id`
    FOREIGN KEY (`site_id`)
    REFERENCES `cosmos`.`site` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cosmos`.`interview_has_indicator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cosmos`.`interview_has_indicator` (
  `interview_id` INT UNSIGNED NOT NULL,
  `indicator_id` INT UNSIGNED NOT NULL,
  `update_timestamp` TIMESTAMP NOT NULL,
  `create_timestamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`interview_id`, `indicator_id`),
  INDEX `fk_indicator_id` (`indicator_id` ASC),
  INDEX `fk_interview_id` (`interview_id` ASC),
  CONSTRAINT `fk_interview_has_indicator_interview_id`
    FOREIGN KEY (`interview_id`)
    REFERENCES `cosmos`.`interview` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interview_has_indicator_indicator_id`
    FOREIGN KEY (`indicator_id`)
    REFERENCES `cosmos`.`indicator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
