<?php
/**
 * module.class.php
 */

namespace cosmos\service\<SUBJECT>;
use cenozo\lib, cenozo\log, cosmos\util;

/**
 * This code was automatically generated by aux/sync_with_opal
 */
class module extends \cosmos\service\data_module {}
