<?php
/**
 * <SUBJECT>.class.php
 * @filesource
 */

namespace cosmos\database;
use cenozo\lib, cenozo\log, cosmos\util;

/**
 * <SUBJECT>: record
 * This code was automatically generated by aux/sync_with_opal
 */
class <SUBJECT> extends base_data {}
